### ISSUE TITLE
Bad credentials Error

### ISSUE THREAD

**Issue by geoperez** [gimenete/eslint-action#18]
I just copied the snippet from the Workflow editor into my JS project:

```yaml
name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
```

And I'm getting the following error:

```
Run gimenete/eslint-action@1.0
/usr/bin/docker run --name e4e3a75cdf60b35fd4e0bbe661bc2e5e5bd1e_3efb5b --label 2e4e3a --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/tubular-nodejs/tubular-nodejs":"/github/workspace" 2e4e3a:75cdf60b35fd4e0bbe661bc2e5e5bd1e
added 416 packages from 247 contributors and audited 1597 packages in 8.28s
found 5 vulnerabilities (1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Error Error: Received status code 401
    at IncomingMessage.res.on (/action/lib/request.js:13:25)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
##[error]Docker run failed with exit code 1
```

**Comment by raccoonback** [comment]
It requests the ["check-runs"](https://developer.github.com/v3/checks/runs/) API with Authorization header to annotate fail case. so I think that you need **"GITHUB_TOKEN"** environment variable.

https://github.com/gimenete/eslint-action/blob/1bbfd5ba0d9e42a04050fa38f6b4eeeacabd9574/lib/run.js#L16

```yaml
// ...
    steps:
    - uses: actions/checkout@v1
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  // here
// ...
```
