### ISSUE TITLE
How to use/configure this action?

### ISSUE THREAD

**Issue by fusion2004** [gimenete/eslint-action#3]
Hi, I'm having a little trouble figure out how to use this action. At first, I was getting a GitHub authentication error, but I was able to figure out I needed to pass the `GITHUB_TOKEN` environment variable / secret to the action. It's still not working for me though, and I'm getting this error:
```
Error Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eslint (/action/lib/run.js:38:18)
    at run (/action/lib/run.js:102:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[error]Docker run failed with exit code 1
```

Here's the current config I'm using:
```
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Can you advise me on what I'm missing?
