### ISSUE TITLE
Missing Diff Anotations? 

### ISSUE THREAD

**Issue by JacobJaffe** [gimenete/eslint-action#4]
First off, thanks for this action! Great to not have to pull in a separate service for a fast check. 

I'm running a config for pull requests; this is giving a success / failure check, but isn't giving diff annotations. What's the expected behavior for this / is this not meant for PR config?

Also, in the `EsLint Checks` logs, the errors are not logged, only the count at the end:

```
...
 found 1377 vulnerabilities (1375 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
1 error(s), 0 warning(s) found
##[error]Docker run failed with exit code 78
```

This would be much more helpful IMO if this also listed the errors.

my config: 

```
name: Linter

on: [pull_request]

jobs:
  es-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
