### ISSUE TITLE
[Question] Does this Action work with v2 GitHub Actions

### ISSUE THREAD

**Issue by pruett** [gimenete/eslint-action#6]
I've been looking to trigger a new Check Run from a GitHub Action and have looked at your repository as an example.

First, this doesn't seem to work (no additional Check Run) is spawned in my PR. I'm using GitHub Actions v2 and curious if you're aware of this or have any additional information.

For example...

**.github/workflows/main.yml**
```yaml
name: checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: npm install

      - name: ESLint checks
         uses: gimenete/eslint-action@1.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Your action runs and I see the output of:

```
2 error(s), 0 warning(s) found
 ##[error]Docker run failed with exit code 78
```

But no additional Check Run was created like in your screenshot.

Do you know if this is a GitHub issue (Actions being in Beta, etc.) or is there something more obvious I'm missing?

Thanks.
